### ISSUE TITLE
Usage without dependency annotation

### ISSUE THREAD

**Issue by phaq01** [PillowPillow/angular-property-binder#1]
I would like to use property binder without annotating the the dependencies, just like 
angular.controller('MyController', function(propertyBinder) { ... }); (also without MyController.$inject = [...]).
Also I cannot use PropertyBinder.services.binder as a controller parameter because of the dots.
Is there a way, I can do that?

**Comment by PillowPillow** [comment]
Hi, there is no way to do what you want without array notation. 
`angular(..).xxx('name', [xxx, function() {}])`
However you could wrap PropertyBinder with a custom service and call it in all your application.
Try something like that:

``` javascript
angular.module('yourmodule')
.service('wrapper', ['PropertyBinder.services.binder', function(binder) { return binder; }])
.controller('somecontroller', function(wrapper) {
//do something
})
```

I implemented the dot notation to dodge any conflict with other libraries and i don't want to remove this spec.
Moreover I highly recommend you to use the array notation for you dependency injections because without it the minification will break your code.

**Comment by phaq01** [comment]
Thanks for the workaround! I run ng-annotate in my build step, which adds the array annotation automatically.
